tools:
  exceptions:
    client: https://sentry.io/organizations/dcsil/projects/client/?project=6036649
    server: https://sentry.io/organizations/dcsil/projects/server/?project=5949857
  logging: https://app.logdna.com/d2cb803c28/logs/view
  database:
    test: https://data.heroku.com/datastores/351f1ee0-2b11-4607-8e92-58073ca5881b
    prod: https://data.heroku.com/datastores/03408426-288d-471d-a239-d9cd39818fbe
  ci: https://github.com/dcsil/Inforum/actions/workflows/ci_pipeline.yml

services:
  production:
    client: https://inforum-client.herokuapp.com/
    server: https://inforum-server.herokuapp.com/api

docs:
  getting_started: ./README.md
      
commands:
  bootstrap: script/bootstrap
  database:
    migrate: cd server; npx sequelize-cli db:migrate
    seed: cd server; npx sequelize-cli db:seed:all
  test: cd server; npm test
  client: cd client; npm start
  server: cd server; npm start