name: CI-pipeline

on:
  push: # test purpose
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: | 
          app/server/package-lock.json 
          app/client/package-lock.json

    # - name: Install client dependencies
    #   working-directory: 'app/client'
    #   run: npm install

    # - name: Client side unit tests
    #   working-directory: 'app/client'
    #   run: npm test

    - name: Install server dependencies
      working-directory: 'app/server'
      run: npm install
      
    - name: Server side unit tests
      working-directory: 'app/server'
      run: npm test
      env:
          SERVER_ENV: 'ci'
          DATABASE_URL: ${{ secrets.HEROKU_TEST_DB_URL }}