name: CI-pipeline

on:
  workflow_dispatch:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20 

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: | 
          app/server/package-lock.json 

    - name: Install server dependencies
      working-directory: 'app/server'
      run: npm install
    
    - name: Run migration
      working-directory: 'app/server'
      run: npx sequelize db:migrate --env=test
      env:
          SERVER_ENV: 'test'
          DATABASE_URL: ${{ secrets.HEROKU_TEST_DB_URL }}

    - name: Clear db
      working-directory: 'app/server'
      run: npx sequelize db:seed:undo:all --env=test
      env:
          SERVER_ENV: 'test'
          DATABASE_URL: ${{ secrets.HEROKU_TEST_DB_URL }}

    - name: Seed db
      working-directory: 'app/server'
      run: npx sequelize db:seed:all --env=test
      env:
          SERVER_ENV: 'test'
          DATABASE_URL: ${{ secrets.HEROKU_TEST_DB_URL }}

    - name: Server side unit tests
      working-directory: 'app/server'
      run: npm test
      env:
          SERVER_ENV: 'test'
          DATABASE_URL: ${{ secrets.HEROKU_TEST_DB_URL }}

    - name: Install client dependencies
      working-directory: 'app/client'
      run: npm install

    - name: Run jest tests for client
      working-directory: 'app/client'
      run: npm test -- --coverage --watchAll=false
    
    # - name: Upload coverage to Code Climate
    #   uses: paambaati/codeclimate-action@v2.7.5
    #   env:
    #     CC_TEST_REPORTER_ID: 7f3833bca12b7ae136f3e60b370197a730d94f6a2ed2daa6c7eefef3ed506b38
    #   with:
    #     workingDirectory: 'app/client'
    #     coverageCommand: npm test -- --coverage --watchAll=false
  
    - name: "Upload to CodeClimate"
      working-directory: 'app/client'
      env:
        CC_TEST_REPORTER_ID: 7f3833bca12b7ae136f3e60b370197a730d94f6a2ed2daa6c7eefef3ed506b38
      run: |
          export GIT_BRANCH="${GITHUB_REF##*/}" 
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter format-coverage -t lcov 
          ./cc-test-reporter upload-coverage --id $CC_TEST_REPORTER_ID
